services:
  php:
    build:
      context: ./project/docker/php
      dockerfile: Dockerfile
    container_name: balikobot3_php
    working_dir: /var/www/project
    ports:
      - "9000:80"
    volumes:
      - .:/var/www
    networks:
      - symfony_network

  nginx:
    image: nginx:alpine
    container_name: balikobot3_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./project/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - symfony_network

networks:
  symfony_network:

volumes:
  db_data: